# Generated by Django 4.2.11 on 2024-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('HP', models.IntegerField(null=True)),
                ('Attack', models.IntegerField(null=True)),
                ('Defense', models.IntegerField(null=True)),
                ('Special_Attack', models.IntegerField(null=True)),
                ('Special_Defense', models.IntegerField(null=True)),
                ('Speed', models.IntegerField(null=True)),
                ('Element', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
